### ISSUE TITLE
Won't compile on OSX with GHC 8.0.1

### ISSUE THREAD

**Issue by joseedil** [haskell-foundation/foundation#232]
This is FYI only. 

Relevante message is
```
[124 of 124] Compiling Foundation.Check ( Foundation/Check.hs, dist/dist-sandbox-149f5139/build/Foundation/Check.p_o ) [Foundation.Check.Arbitrary changed]
duplicate symbol _foundationzm0zi0zi5zm2y8kRfBAQmDFaEaZZhtknbm_FoundationziCheckziGen_GenParams_closure in:
    dist/dist-sandbox-149f5139/build/Foundation/Check.dyn_o
    dist/dist-sandbox-149f5139/build/Foundation/Check/Gen.dyn_o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)
cabal: Leaving directory '/Volumes/HD2/Development/Haskell/sourceGraph/foundation'
cabal: Error: some packages failed to install:
foundation-0.0.5 failed during the building phase. The exception was:
ExitFailure 1
```

After struggling with the code, I updated my box to GHC 8.0.2 and it worked.

**Comment by vincenthz** [comment]
this is a known bug of ghc 8.0.1 on sierra, which was fixed in ghc 8.0.2. Nothing to do with foundation

**Comment by vincenthz** [comment]
Actually, re-reading the error message I'm not sure this is exactly this. but in any case generally using the latest version of a stable compiler is the right thing to do.
