### ISSUE TITLE
fail not in scope with GHC 8.8

### ISSUE THREAD

**Issue by andrewthad** [haskell-foundation/foundation#517]
`basement` doesn't compile with GHC 8.8. The error message is:

```
Basement/Block/Base.hs:398:9: error:
    Not in scope: ‘fail’
    Perhaps you meant ‘Data.List.tail’ (imported from Data.List)
    |
398 |         arr@(Block arrBa) <- makeTrampoline
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Basement/Block/Base.hs:481:9: error:
    Not in scope: ‘fail’
    Perhaps you meant ‘Data.List.tail’ (imported from Data.List)
    |
481 |         b@(Block ba) <- unsafeFreeze pinnedMb
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I think that `fail` just needs to be explicitly imported.

**Comment by vincenthz** [comment]
it's hard to understand why ghc would put a `fail` in this code, there's no pattern cases/opportunity to fail here but it seems to generate code with it for the general case.

**Comment by endgame** [comment]
Note that #520 didn't completely fix this. I'm hacking around this to get another project building, and the following modules were also affected:
```
Basement.Block
Basement.Block.Mutable
Basement.BoxedArray
Basement.String
Basement.UArray
Basement.UArray.Base
Basement.UTF8.Base
```
I just stuck `import Control.Monad` in them, and got on with my life. You might want to solve this properly, a la #520.

**Comment by endgame** [comment]
`foundation` is also not `MonadFail`-ready, and I mention this here because it starts causing compile errors in GHC 8.8. These modules are affected:
```
Foundation.Check.Main
Foundation.Monad.Except
Foundation.Network.IPv6
Foundation.Parser
```
I am not providing a PR because I'm just doing disgusting hacks to keep moving on my main objective. The test suite also broke, so I turned it off.
