### ISSUE TITLE
foundation 0.0.2 fails to compile on ghc 8.0.1 on armhf

### ISSUE THREAD

**Issue by andrewufrank** [haskell-foundation/foundation#173]
i get the error message 
````
Foundation/Primitive/Types.hs:363:41: error:
    • Couldn't match expected type ‘Word8’ with actual type ‘Int8’
    • In the first argument of ‘CChar’, namely
        ‘(primBaUIndex ba (Offset n :: Offset Int8))’
      In the expression:
        CChar (primBaUIndex ba (Offset n :: Offset Int8))
      In an equation for ‘primBaUIndex’:
          primBaUIndex ba (Offset n)
            = CChar (primBaUIndex ba (Offset n :: Offset Int8))
````

when compilling with 
````
ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1
frank@ascona:~$ ghc -v
Glasgow Haskell Compiler, Version 8.0.1, stage 2 booted by GHC version 8.0.1
Using binary package database: /usr/lib/ghc/package.conf.d/package.cache
Using binary package database: /home/frank/.ghc/arm-linux-8.0.1/package.conf.d/package.cache
loading package database /usr/lib/ghc/package.conf.d
loading package database /home/frank/.ghc/arm-linux-8.0.1/package.conf.d
wired-in package ghc-prim mapped to ghc-prim-0.5.0.0
wired-in package integer-gmp mapped to integer-gmp-1.0.0.1
wired-in package base mapped to base-4.9.0.0
wired-in package rts mapped to rts
wired-in package template-haskell mapped to template-haskell-2.11.0.0
wired-in package ghc mapped to ghc-8.0.1
wired-in package dph-seq not found.
wired-in package dph-par not found.
````
the package compiles ok on amd-64 (both install haskell-platform), the error seems to be trapped only in the armhf version of ghc.

````
ghc -v
Glasgow Haskell Compiler, Version 8.0.1, stage 2 booted by GHC version 8.0.1
Using binary package database: /usr/lib/ghc/package.conf.d/package.cache
Using binary package database: /home/frank/.ghc/x86_64-linux-8.0.1/package.conf.d/package.cache
loading package database /usr/lib/ghc/package.conf.d
loading package database /home/frank/.ghc/x86_64-linux-8.0.1/package.conf.d
wired-in package ghc-prim mapped to ghc-prim-0.5.0.0
wired-in package integer-gmp mapped to integer-gmp-1.0.0.1
wired-in package base mapped to base-4.9.0.0
wired-in package rts mapped to rts
wired-in package template-haskell mapped to template-haskell-2.11.0.0
wired-in package ghc mapped to ghc-8.0.1
wired-in package dph-seq not found.
wired-in package dph-par not found.
````

thank you for fixing!

**Comment by 2bdkid** [comment]
I'm getting the same error. GHC 8.0.1 on a Raspberry Pi 2.
```
Foundation/Primitive/Types.hs:363:41: error:
    • Couldn't match expected type ‘Word8’ with actual type ‘Int8’
    • In the first argument of ‘CChar’, namely
        ‘(primBaUIndex ba (Offset n :: Offset Int8))’
      In the expression:
        CChar (primBaUIndex ba (Offset n :: Offset Int8))
      In an equation for ‘primBaUIndex’:
          primBaUIndex ba (Offset n)
            = CChar (primBaUIndex ba (Offset n :: Offset Int8))

Foundation/Primitive/Types.hs:365:45: error:
    • Couldn't match type ‘Int8’ with ‘Word8’
      Expected type: prim Word8
        Actual type: prim Int8
    • In the second argument of ‘(<$>)’, namely
        ‘primMbaURead mba (Offset n :: Offset Int8)’
      In the expression:
        CChar <$> primMbaURead mba (Offset n :: Offset Int8)
      In an equation for ‘primMbaURead’:
          primMbaURead mba (Offset n)
            = CChar <$> primMbaURead mba (Offset n :: Offset Int8)

Foundation/Primitive/Types.hs:369:45: error:
    • Couldn't match expected type ‘Word8’ with actual type ‘Int8’
    • In the second argument of ‘($)’, namely
        ‘primAddrIndex addr (Offset n :: Offset Int8)’
      In the expression:
        CChar $ primAddrIndex addr (Offset n :: Offset Int8)
      In an equation for ‘primAddrIndex’:
          primAddrIndex addr (Offset n)
            = CChar $ primAddrIndex addr (Offset n :: Offset Int8)

Foundation/Primitive/Types.hs:371:46: error:
    • Couldn't match type ‘Int8’ with ‘Word8’
      Expected type: prim Word8
        Actual type: prim Int8
    • In the second argument of ‘(<$>)’, namely
        ‘primAddrRead addr (Offset n :: Offset Int8)’
      In the expression:
        CChar <$> primAddrRead addr (Offset n :: Offset Int8)
      In an equation for ‘primAddrRead’:
          primAddrRead addr (Offset n)
            = CChar <$> primAddrRead addr (Offset n :: Offset Int8)
```

**Comment by kmihelich** [comment]
That commit fixes the build issue for Types.hs, but has caused a new failure in ASCII.hs on ARM:

```
[60 of 89] Compiling Foundation.String.ASCII ( Foundation/String/ASCII.hs, dist/build/Foundation/String/ASCII.o )

Foundation/String/ASCII.hs:55:21: error:
    • Couldn't match expected type ‘Word8’ with actual type ‘Int8’
    • In the pattern: I8# i
      In the pattern: CChar (I8# i)
      In an equation for ‘ccharToChar’:
          ccharToChar (CChar (I8# i)) = C# (chr# i)

Foundation/String/ASCII.hs:57:29: error:
    • Couldn't match expected type ‘Word8’ with actual type ‘Int8’
    • In the first argument of ‘CChar’, namely ‘(I8# (ord# i))’
      In the expression: CChar (I8# (ord# i))
      In an equation for ‘charToCChar’:
          charToCChar (C# i) = CChar (I8# (ord# i))
```

**Comment by vincenthz** [comment]
thanks @kmihelich, I should have sorted this one too now. do let me know if not

**Comment by kmihelich** [comment]
That commit gets it building successfully, thanks.  For some background on what is likely the root of this issue, the C char type on ARM and PPC is unsigned, as opposed to being signed on x86.

**Comment by vincenthz** [comment]
yep thanks. I didn't realized ghc would follow the crazies of C for this :\
