### ISSUE TITLE
Foundation.Conduit.Internal does not build on GHC 9.0.1

### ISSUE THREAD

**Issue by danwdart** [haskell-foundation/foundation#551]
```
Foundation/Conduit/Internal.hs:129:55: error:
    • Couldn't match type: forall a2.
                           (a -> Pipe i i o () m a2) -> Pipe i i o () m a2
                     with: (a -> Pipe i i o () m a1) -> Pipe i i o () m a1
      Expected: Conduit i o m a
                -> (a -> Pipe i i o () m a1) -> Pipe i i o () m a1
        Actual: Conduit i o m a
                -> forall a1. (a -> Pipe i i o () m a1) -> Pipe i i o () m a1
    • In the first argument of ‘flip’, namely ‘unConduit’
      In the first argument of ‘(.)’, namely ‘flip unConduit rest’
      In the second argument of ‘(.)’, namely
        ‘flip unConduit rest . onExc’
    • Relevant bindings include
        m :: m (Pipe i i o () m a)
          (bound at Foundation/Conduit/Internal.hs:128:19)
        go :: Pipe i i o () m a -> Pipe i i o () m a1
          (bound at Foundation/Conduit/Internal.hs:128:9)
        rest :: a -> Pipe i i o () m a1
          (bound at Foundation/Conduit/Internal.hs:127:43)
        onExc :: e -> Conduit i o m a
          (bound at Foundation/Conduit/Internal.hs:127:24)
        c0 :: forall a1. (a -> Pipe i i o () m a1) -> Pipe i i o () m a1
          (bound at Foundation/Conduit/Internal.hs:127:20)
        catch :: Conduit i o m a
                 -> (e -> Conduit i o m a) -> Conduit i o m a
          (bound at Foundation/Conduit/Internal.hs:127:5)
    |
129 |             PipeM $ catch (liftM go m) (return . flip unConduit rest . onExc)
```

https://github.com/haskell-foundation/foundation/blob/58568e9f5368170d272000ecf16ef64fb91d0732/foundation/Foundation/Conduit/Internal.hs#L129

**Comment by danwdart** [comment]
For a workaround, I think this Nix derivation override helps:

```nix
{
  foundation = (self.callHackage "foundation" "0.0.25" {}).overrideDerivation(self: {
    prePatch = ''
      sed -i 's/return . flip unConduit rest . onExc/\\x -> return \$ unConduit (onExc x) rest/g' Foundation/Conduit/Internal.hs
    '';
  });
}
```

**Comment by EmilGedda** [comment]
I believe this issue is fixed by the PR #540, which in turn would unblock the GHC 9 migration issue #549.

**Comment by andreasabel** [comment]
Blocking https://github.com/ocharles/weeder/issues/65.
