### ISSUE TITLE
`basement` package fails to compile on GHC 9.2.2 (pre-release)

### ISSUE THREAD

**Issue by maerten** [haskell-foundation/foundation#562]
```
basement             > [19 of 84] Compiling Basement.Numerical.Conversion
basement             >
basement             > /private/var/folders/0c/zmpjp7l568xcvnt49pkkn5p00000gn/T/stack-821293c49c9c7b84/basement-0.0.12/Basement/Numerical/Conversion.hs:84:46: error:
basement             >     • Couldn't match expected type ‘Word32#’ with actual type ‘Word#’
basement             >     • In the first argument of ‘W32#’, namely
basement             >         ‘(uncheckedShiftRL# w64 32#)’
basement             >       In the first argument of ‘Word32x2’, namely
basement             >         ‘(W32# (uncheckedShiftRL# w64 32#))’
basement             >       In the expression:
basement             >         Word32x2
basement             >           (W32# (uncheckedShiftRL# w64 32#)) (W32# (narrow32Word# w64))
basement             >    |
basement             > 84 | word64ToWord32s (W64# w64) = Word32x2 (W32# (uncheckedShiftRL# w64 32#)) (W32# (narrow32Word# w64))
basement             >    |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^
basement             >
basement             > /private/var/folders/0c/zmpjp7l568xcvnt49pkkn5p00000gn/T/stack-821293c49c9c7b84/basement-0.0.12/Basement/Numerical/Conversion.hs:84:81: error:
basement             >     • Couldn't match expected type ‘Word32#’ with actual type ‘Word#’
basement             >     • In the first argument of ‘W32#’, namely ‘(narrow32Word# w64)’
basement             >       In the second argument of ‘Word32x2’, namely
basement             >         ‘(W32# (narrow32Word# w64))’
basement             >       In the expression:
basement             >         Word32x2
basement             >           (W32# (uncheckedShiftRL# w64 32#)) (W32# (narrow32Word# w64))
basement             >    |
basement             > 84 | word64ToWord32s (W64# w64) = Word32x2 (W32# (uncheckedShiftRL# w64 32#)) (W32# (narrow32Word# w64))
basement             >    |                                                                                 ^^^^^^^^^^^^^^^^^
```

**Comment by maerten** [comment]
my bad, the latest version does actually compile successfully on 9.2.2
