### ISSUE TITLE
Tighten bounds on base

### ISSUE THREAD

**Issue by vmchale** [haskell-foundation/foundation#574]
foundation-0.0.29 doesn't build with base 4.18:

```
Foundation/Tuple.hs:29:10: error: [GHC-39999]
    • No instance for ‘Functor (Tuple2 a)’
        arising from the head of a quantified constraint
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Bifunctor Tuple2’
   |
29 | instance Bifunctor Tuple2 where
   |          ^^^^^^^^^^^^^^^^
```

**Comment by ysangkok** [comment]
foundation v0.0.30 was released and works on GHC 9.6/base-4.18.
