### ISSUE TITLE
foundation doesn't compile on 9.6.1

### ISSUE THREAD

**Issue by GeorgeCo** [haskell-foundation/foundation#576]
foundation doesn't compile on 9.6.1
```
[ 83 of 103] Compiling Foundation.Tuple ( Foundation/Tuple.hs, dist/build/Foundation/Tuple.o, dist/build/Foundation/Tuple.dyn_o )

Foundation/Tuple.hs:29:10: error: [GHC-39999]
    • No instance for ‘Functor (Tuple2 a)’
        arising from the head of a quantified constraint
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Bifunctor Tuple2’
   |
29 | instance Bifunctor Tuple2 where
   |          ^^^^^^^^^^^^^^^^
```

**Comment by ysangkok** [comment]
This was addressed in v0.0.30: https://github.com/haskell-foundation/foundation/commit/44ec11afdb6c64639aeae5a4a062186d49d3c9f1

I believe this can be closed.
